[package]
name = "whitehole"
# reminder before releasing to crates.io:
# - Remove path dependencies (e.g. the macro).
# - Update README.md & CHANGELOG.md.
# - Create version git tag.
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["DiscreteTom <discrete_tom@outlook.com>"]
repository = "https://github.com/DiscreteTom/whitehole"

[dependencies]
regex = { version = "1.9.4" }
whitehole_macros = { path = "./macros" }
